const {chromium}=require('C:/Users/Admin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:1366,height:900}}),errors=[],missing=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)missing.push(r.url());});
 await page.goto(process.env.APP_TEST_BASE||'http://127.0.0.1:8765/index.html');await page.waitForSelector('.app-playground');
 assert.equal(await page.locator('.side-nav').isVisible(),false);assert.equal(await page.locator('.app-bottom-nav button').count(),3);assert.equal(await page.locator('.app-world-door').count(),3);assert.equal(await page.locator('[data-continue]').count(),0);
 for(const [width,height] of [[1366,900],[1024,768],[768,1024],[390,844],[320,740]]){await page.setViewportSize({width,height});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`tests/world-home-${width}.png`,fullPage:true});}
 await page.setViewportSize({width:1366,height:900});await page.locator('[data-start-adventure]').click();await page.waitForFunction(()=>currentGame==='spin');assert(await page.locator('.app-header').isHidden());assert(await page.locator('.app-bottom-nav').isHidden());assert(await page.locator('.reward-game-hud').isVisible());assert(await page.locator('[data-shell-action="drawer"]').isHidden());
 await page.locator('.app-game-more>summary').click();await page.locator('[data-shell-action="teacher"]').click();assert(await page.locator('#teacherPanel').isVisible());await page.locator('#closeTeacher').count().then(async n=>{if(n)await page.locator('#closeTeacher').click();else await page.evaluate(()=>document.querySelector('#teacherPanel').hidden=true);});
 await page.screenshot({path:'tests/world-game.png',fullPage:true});await page.locator('[data-shell-action="back"]').click();await page.waitForSelector('#lessonApp [data-activity]');
 await page.evaluate(()=>LearningApp.go('#/unit/2'));assert.equal(await page.locator('.app-lesson-stop').count(),6);assert.equal(await page.locator('[data-lesson="1"]').getAttribute('aria-current'),'step');assert.equal(await page.locator('[data-lesson="6"]').getAttribute('aria-disabled'),'true');await page.screenshot({path:'tests/world-journey.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'tests/world-journey-mobile.png',fullPage:true});
 await page.locator('[data-app-tab="home"]').click();await page.waitForSelector('[data-continue]');await page.reload();await page.waitForSelector('[data-continue]');assert.match(await page.locator('[data-continue]').getAttribute('href'),/activity=spin/);
 await page.locator('[data-manage-learner]').click();await page.locator('#rewardNewStudent input').fill('Mai');await page.locator('#rewardNewStudent button').click();await page.locator('[data-reward-close]').click();assert.equal(await page.locator('[data-continue]').count(),0);assert.match(await page.locator('.app-greeting').textContent(),/Mai/);
 await page.locator('[data-app-tab="stars"]').click();assert(await page.locator('.reward-book').isVisible());await page.selectOption('#rewardStudent','default');await page.locator('[data-reward-close]').click();assert.match(await page.locator('[data-continue]').getAttribute('href'),/activity=spin/);
 await page.locator('.shell-letter-world').click();await page.waitForSelector('#spaceLetters');assert(await page.locator('#spaceLetters').isVisible());await page.locator('[data-app-tab="lessons"]').click();await page.waitForSelector('.app-journey');
 await page.evaluate(()=>LearningApp.go('#/letters/game/'+LearningConfig.independentGames[0]));await page.waitForSelector('.app-game-more');await page.locator('.app-game-more>summary').click();await page.locator('[data-shell-action="sound"]').click();await page.locator('.app-game-more>summary').click();await page.locator('[data-shell-action="sound"]').click();await page.locator('[data-shell-action="back"]').click();assert(await page.locator('#spaceLetters').isVisible());
 await page.setViewportSize({width:1366,height:768});await page.evaluate(()=>LearningApp.go('#/unit/3/lesson/2?mode=practice&activity=talk-to-toy-buddy'));await page.waitForSelector('.l2-scene[data-phase="listening"]');await page.screenshot({path:'tests/world-toy-buddy.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'tests/world-toy-buddy-mobile.png',fullPage:true});await page.evaluate(()=>LearningApp.go('#/'));
 await page.evaluate(()=>LearningProgress.remember('#/unit/99/lesson/1?activity=removed'));await page.locator('[data-app-tab="home"]').click();await page.waitForSelector('[data-start-adventure]');assert.equal(await page.locator('[data-continue]').count(),0);
 assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);await browser.close();console.log('PASS world app: new playground, three worlds, bottom navigation, first game, learner resume/isolation, six-stop journey, current/planned lesson, focused game, More/Teacher, Letter Land and five viewport sizes.');
})().catch(e=>{console.error(e);process.exit(1)});
