const {chromium}=require('C:/Users/Admin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:1366,height:900}}),errors=[],missing=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)missing.push(r.url());});
 await page.addInitScript(()=>{window.clickEvents=[];window.sampledClicks=[];document.addEventListener('learning:ui-sound',e=>clickEvents.push(e.detail));const start=AudioBufferSourceNode.prototype.start;AudioBufferSourceNode.prototype.start=function(){const data=this.buffer.getChannelData(0);let peak=0;for(const x of data)peak=Math.max(peak,Math.abs(x));sampledClicks.push({duration:this.buffer.duration,peak});return start.apply(this,arguments);};const play=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(){if(!this.learningSfx)this.playbackRate=4;return play.call(this);};});
 await page.goto(process.env.CLICK_TEST_BASE||'http://127.0.0.1:8765/index.html');await page.waitForFunction(()=>!!LearningApp&&!!LearningClickSound);
 await page.locator('[data-start-adventure]').click();await page.waitForFunction(()=>clickEvents.length>0);assert(await page.evaluate(()=>sampledClicks.some(a=>a.duration>=.085&&a.duration<=.15&&a.peak>.7)));
 await page.evaluate(()=>LearningApp.go('#/unit/3/lesson/1?mode=practice&activity=u3learn'));await page.waitForSelector('#u3Hero');await page.waitForTimeout(800);
 const before=await page.evaluate(()=>clickEvents.length);await page.locator('#u3NextToy').click();await page.waitForFunction(n=>clickEvents.length>n,before);assert(await page.evaluate(n=>clickEvents.slice(n).some(e=>e.kind==='next'),before));
 // A toy tap changes the scene and starts real voice audio, but its sampled UI cue survives.
 await page.waitForTimeout(250);const n=await page.evaluate(()=>clickEvents.length);await page.locator('.u3-thumbs .u3-card').last().click();await page.waitForFunction(n=>clickEvents.length>n,n);assert(await page.evaluate(n=>clickEvents.slice(n).some(e=>e.file==='ui-click3.wav'&&e.duration>.08),n));
 const action=async name=>{await page.locator('.app-game-more>summary').click();await page.locator(`[data-shell-action="${name}"]`).click();};
 await action('sound');const muted=await page.evaluate(()=>clickEvents.length);await page.locator('#u3NextToy').click();await page.waitForTimeout(180);assert.equal(await page.evaluate(()=>clickEvents.length),muted);await action('sound');await page.waitForFunction(n=>clickEvents.length>n,muted);assert(await page.evaluate(n=>clickEvents.slice(n).some(e=>e.kind==='toggle'),muted));
 await action('teacher');await page.locator('#feedbackSoundPreview').click();assert(await page.locator('#feedbackSoundPreview').isVisible());await page.waitForTimeout(170);
 await page.evaluate(()=>{document.querySelector('#teacherPanel').classList.remove('open');document.querySelector('#teacherPanel').hidden=true;LearningApp.go('#/unit/3/lesson/2?mode=practice&activity=talk-to-toy-buddy');});await page.waitForFunction(()=>Unit3Lesson2.current()?.phase==='listening');
 await page.evaluate(()=>{const s=Unit3Lesson2.current();s.phase='recording';s.refresh();});const recording=await page.evaluate(()=>clickEvents.length);await page.evaluate(()=>LearningClickSound.play(document.querySelector('#l2Mic')));await page.waitForTimeout(160);assert.equal(await page.evaluate(()=>clickEvents.length),recording);
 assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);await browser.close();console.log('PASS sampled click audio: real Web Audio buffers, audible 86–139 ms samples, first navigation click, Meet the Toys next/selection with voice and scene refresh, mute/unmute, teacher preview and microphone suppression.');
})().catch(e=>{console.error(e);process.exit(1);});
